version: '3.3'

services:
  travel-diary-proxy-server-project:
    image: travel-diary-proxy-server-project
    container_name: travel-diary-proxy-server-project
    command: /usr/sbin/apache2ctl -D FOREGROUND
    volumes:
      - ./src/:/var/www/html
    extra_hosts:
      - traveldiary.com:${HOST_IP=127.0.0.1}
    ports:
      - '40022:22'
      - '40080:80'
      - '48080:8080'
    expose:
      - '40022'
      - '40080'
      - '48080'
